# Generated by Django 4.1.3 on 2022-12-02 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_seo_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='related',
            field=models.ManyToManyField(blank=True, to='home.page'),
        ),
    ]
