# Generated by Django 4.1.3 on 2022-12-02 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_page_related'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prices',
        ),
        migrations.RemoveField(
            model_name='page',
            name='related',
        ),
    ]
