# Generated by Django 4.1.3 on 2022-12-04 23:49

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_prices_remove_page_related'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
