# Generated by Django 4.1.3 on 2022-12-05 11:44

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_page_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[2560, 1440], upload_to='pages/'),
        ),
    ]
