# Generated by Django 4.1.3 on 2022-12-05 14:53

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_page_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seo',
            options={},
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[2560, 2560], upload_to='pages/'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[1200, 630], upload_to='seo'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('intro', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('aspect_ratio', models.CharField(choices=[('original', 'Original'), ('landscape', 'Landscape 16x9'), ('portrait', 'Portrait 9x16'), ('square', 'Square 1x1')], default='Original', max_length=20)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[2560, 1440], upload_to='articles/')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.page')),
            ],
        ),
    ]
