# Generated by Django 4.1.3 on 2022-12-05 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_name_page_title_remove_article_aspect_ratio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
