# Generated by Django 4.1.3 on 2022-12-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_page_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='title',
            new_name='name',
        ),
    ]
