# Generated by Django 4.1.3 on 2022-12-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_title_page_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='intro',
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
