# Generated by Django 4.1.3 on 2022-12-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_article_intro_article_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlevideo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
