# Generated by Django 4.1.3 on 2022-12-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_articleimage_description_articlevideo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='title_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='description_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articleimage',
            name='title_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='articlevideo',
            name='description_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlevideo',
            name='title_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='description_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='section',
            name='title_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='seo',
            name='description_no',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='seo',
            name='keywords_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='title_no',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
