# Generated by Django 4.1.3 on 2022-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_article_body_no_article_subtitle_no_article_title_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
