# Generated by Django 4.1.3 on 2022-12-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_section_description_section_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='section',
            name='subtitle_no',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
