# Generated by Django 4.1.3 on 2022-12-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_section_description_no_section_subtitle_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='description',
        ),
        migrations.RemoveField(
            model_name='section',
            name='description_no',
        ),
    ]
