# Generated by Django 4.1.3 on 2022-12-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_section_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='url',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
