# Generated by Django 4.1.3 on 2022-12-07 14:44

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_articleimage_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('title_no', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('description_no', models.TextField(blank=True)),
                ('aspect_ratio', models.CharField(choices=[('original', 'Original'), ('landscape', 'Landscape 16x9'), ('portrait', 'Portrait 9x16'), ('square', 'Square 1x1')], default='Original', max_length=20)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[2560, 2560], upload_to='images/')),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, to='home.article')),
                ('pages', models.ManyToManyField(blank=True, to='home.page')),
                ('sections', models.ManyToManyField(blank=True, to='home.section')),
            ],
        ),
        migrations.CreateModel(
            name='element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('body_no', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, to='home.article')),
                ('pages', models.ManyToManyField(blank=True, to='home.page')),
                ('sections', models.ManyToManyField(blank=True, to='home.section')),
            ],
        ),
    ]
