# Generated by Django 4.1.3 on 2022-12-07 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_image_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='element',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='element',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='image',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='image',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='image',
            name='sections',
        ),
        migrations.AddField(
            model_name='image',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.article'),
        ),
        migrations.AddField(
            model_name='image',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.section'),
        ),
        migrations.DeleteModel(
            name='ArticleImage',
        ),
        migrations.DeleteModel(
            name='element',
        ),
    ]
