# Generated by Django 4.1.3 on 2022-12-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_element_articles_remove_element_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
        migrations.RemoveField(
            model_name='image',
            name='section',
        ),
        migrations.AddField(
            model_name='image',
            name='articles',
            field=models.ManyToManyField(blank=True, to='home.article'),
        ),
        migrations.AddField(
            model_name='image',
            name='pages',
            field=models.ManyToManyField(blank=True, to='home.page'),
        ),
        migrations.AddField(
            model_name='image',
            name='sections',
            field=models.ManyToManyField(blank=True, to='home.section'),
        ),
    ]
