# Generated by Django 4.1.3 on 2022-12-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_image_article_remove_image_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlevideo',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlevideo',
            name='section',
        ),
        migrations.AddField(
            model_name='articlevideo',
            name='articles',
            field=models.ManyToManyField(blank=True, to='home.article'),
        ),
        migrations.AddField(
            model_name='articlevideo',
            name='pages',
            field=models.ManyToManyField(blank=True, to='home.page'),
        ),
        migrations.AddField(
            model_name='articlevideo',
            name='sections',
            field=models.ManyToManyField(blank=True, to='home.section'),
        ),
    ]
