# Generated by Django 4.1.3 on 2022-12-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_articlevideo_article_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleVideo',
            new_name='Video',
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('body_no', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('articles', models.ManyToManyField(blank=True, to='home.article')),
                ('pages', models.ManyToManyField(blank=True, to='home.page')),
                ('sections', models.ManyToManyField(blank=True, to='home.section')),
            ],
        ),
    ]
