# Generated by Django 4.1.3 on 2022-12-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug_no',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
