# Generated by Django 4.1.3 on 2022-12-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_page_slug_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
