# Generated by Django 4.2.30 on 2026-05-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_page_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='articles',
            field=models.ManyToManyField(blank=True, null=True, to='home.article'),
        ),
    ]
