# Generated by Django 4.2.30 on 2026-05-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_video_articles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='aspect_ratio',
            field=models.CharField(choices=[('original', 'Original'), ('landscape', 'Landscape 16x9'), ('portrait', 'Portrait 9x16'), ('square', 'Square 1x1')], default='original', max_length=20),
        ),
    ]
