# Generated by Django 4.2.30 on 2026-05-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_image_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_legacy_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='subtitle_legacy_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_legacy_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='element',
            name='body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='body_legacy_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_legacy_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_legacy_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='description_legacy_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='image',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='title_legacy_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='description_legacy_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='name_legacy_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_en',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='slug_legacy_no',
            field=models.SlugField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='section',
            name='subtitle_en',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='subtitle_legacy_no',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='section',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='title_legacy_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='seo',
            name='description_en',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='description_legacy_no',
            field=models.TextField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='seo',
            name='keywords_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='keywords_legacy_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='seo',
            name='title_legacy_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='description_legacy_no',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='title_legacy_no',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='subtitle_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='body_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='description_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='title_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='description_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='name_no',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug_no',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='subtitle_no',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='title_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='description_no',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='keywords_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seo',
            name='title_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description_no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
