# Generated by Django 4.2.30 on 2026-05-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_article_body_en_article_body_legacy_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body_legacy_no',
        ),
        migrations.RemoveField(
            model_name='article',
            name='subtitle_legacy_no',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_legacy_no',
        ),
        migrations.RemoveField(
            model_name='element',
            name='body_legacy_no',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_legacy_no',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_legacy_no',
        ),
        migrations.RemoveField(
            model_name='image',
            name='description_legacy_no',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title_legacy_no',
        ),
        migrations.RemoveField(
            model_name='page',
            name='description_legacy_no',
        ),
        migrations.RemoveField(
            model_name='page',
            name='name_legacy_no',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug_legacy_no',
        ),
        migrations.RemoveField(
            model_name='section',
            name='subtitle_legacy_no',
        ),
        migrations.RemoveField(
            model_name='section',
            name='title_legacy_no',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='description_legacy_no',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='keywords_legacy_no',
        ),
        migrations.RemoveField(
            model_name='seo',
            name='title_legacy_no',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description_legacy_no',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title_legacy_no',
        ),
    ]
