# Generated by Django 3.2.7 on 2021-11-15 16:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20211115_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, size=[1920, 1920], upload_to='album'),
        ),
    ]
