# Generated by Django 3.2.7 on 2021-11-15 19:40

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=False, quality=100, size=[800, 1200], upload_to='album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=False, quality=100, size=[600, 900], upload_to='artist'),
        ),
    ]
