# Generated by Django 3.2.7 on 2022-11-07 20:20

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20211115_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='order',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=False, quality=80, size=[800, 1200], upload_to='album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=False, quality=80, size=[600, 900], upload_to='artist'),
        ),
    ]
