# Generated by Django 3.2.7 on 2022-11-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_alter_artist_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='order',
            field=models.IntegerField(default=2),
        ),
    ]
