# Generated by Django 3.2.7 on 2022-11-15 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_alter_artist_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='order',
            field=models.IntegerField(default=4),
        ),
    ]
