# Generated by Django 4.1.3 on 2022-11-28 16:37

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0012_album_created_at_album_slug_album_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='order',
            field=models.IntegerField(blank=True, default=builtins.id, null=True),
        ),
    ]
