# Generated by Django 4.1.3 on 2022-11-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0013_alter_artist_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True),
        ),
    ]
