# Generated by Django 4.1.3 on 2022-11-30 09:43

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0014_alter_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=False, quality=80, size=[1920, 1080], upload_to='album'),
        ),
    ]
