# Generated by Django 4.1.3 on 2022-11-30 11:03

import album.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0016_alter_album_image'),
    ]

    operations = [

    ]
