# Generated by Django 4.1.3 on 2022-11-30 11:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0017_album_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=False, null=True, quality=80, size=[1920, 1080], upload_to='album'),
        ),
    ]
