# Generated by Django 4.1.3 on 2022-11-30 12:49

import album.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0019_remove_album_custom_alter_album_image'),
    ]

    operations = [

    ]
