# Generated by Django 4.1.3 on 2022-11-30 15:50

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0020_alter_album_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[200, 200], upload_to='new'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=False, null=True, quality=100, size=[100, 100], upload_to='new'),
        ),
    ]
