# Generated by Django 4.1.3 on 2022-11-30 17:15

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0021_alter_album_image_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[2500, 2500], upload_to='album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[2500, 2500], upload_to='artist'),
        ),
    ]
