# Generated by Django 4.1.3 on 2022-12-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0022_alter_album_image_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True),
        ),
    ]
