# Generated by Django 4.1.3 on 2022-12-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0024_alter_album_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
