# Generated by Django 4.1.3 on 2022-12-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0025_alter_album_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
