# Generated by Django 4.1.3 on 2022-12-02 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_seo_page'),
        ('album', '0027_seo_artist_description_artist_slogan_page_album_seo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='slogan',
        ),
        migrations.AddField(
            model_name='album',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.page'),
        ),
        migrations.AddField(
            model_name='artist',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.page'),
        ),
        migrations.AddField(
            model_name='artist',
            name='seo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.seo'),
        ),
        migrations.AlterField(
            model_name='album',
            name='seo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.seo'),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Seo',
        ),
    ]
