# Generated by Django 4.1.3 on 2022-12-02 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0028_remove_artist_description_remove_artist_slogan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='page',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='page',
        ),
    ]
