# Generated by Django 4.1.3 on 2022-12-02 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_seo_page'),
        ('album', '0029_remove_album_page_remove_artist_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='seo',
        ),
        migrations.AddField(
            model_name='artist',
            name='Page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.page'),
        ),
    ]
