# Generated by Django 4.1.3 on 2022-12-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0030_remove_artist_seo_artist_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True, unique=True),
        ),
    ]
