# Generated by Django 4.1.3 on 2022-12-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0031_alter_album_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True),
        ),
    ]
