# Generated by Django 4.1.3 on 2022-12-05 11:44

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0032_alter_album_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='aspect_ratio',
            field=models.CharField(choices=[('original', 'Original'), ('landscape 16x9', 'Landscape'), ('portrait 9x16', 'Portrait'), ('square 1x1', 'Square')], default='Original', max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[2560, 2560], upload_to='album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=False, null=True, quality=100, size=[2560, 2560], upload_to='artist'),
        ),
    ]
