# Generated by Django 4.1.3 on 2022-12-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0033_album_aspect_ratio_alter_album_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='aspect_ratio',
            field=models.CharField(choices=[('original', 'Original'), ('landscape', 'Landscape 16x9'), ('portrait', 'Portrait 9x16'), ('square', 'Square 1x1')], default='Original', max_length=20),
        ),
    ]
