# Generated by Django 4.1.3 on 2022-12-07 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0034_alter_album_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
