# Generated by Django 4.1.3 on 2022-12-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0035_album_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug_no',
            field=models.SlugField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='slug_no',
            field=models.SlugField(auto_created=True, blank=True, null=True),
        ),
    ]
