# Generated by Django 4.2.30 on 2026-05-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0036_album_slug_no_artist_slug_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='Page',
            new_name='page',
        ),
        migrations.AlterField(
            model_name='album',
            name='aspect_ratio',
            field=models.CharField(choices=[('original', 'Original'), ('landscape', 'Landscape 16x9'), ('portrait', 'Portrait 9x16'), ('square', 'Square 1x1')], default='original', max_length=20),
        ),
    ]
