# Generated by Django 4.2.30 on 2026-05-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0037_rename_page_artist_page_alter_album_aspect_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='slug_en',
            field=models.SlugField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='album',
            name='slug_legacy_no',
            field=models.SlugField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='slug_en',
            field=models.SlugField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='slug_legacy_no',
            field=models.SlugField(auto_created=True, blank=True, null=True),
        ),
    ]
