# Generated by Django 4.2.30 on 2026-05-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0038_album_slug_en_album_slug_legacy_no_artist_slug_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug_legacy_no',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='slug_legacy_no',
        ),
    ]
